### ISSUE TITLE
Question: Why is this not found in visual studio gallery?

### ISSUE THREAD

**Issue by sherry-ummen** [CausalityLtd/VS-pony#1]

**Comment by andymcn** [comment]
The pony compiler is a stand alone tool, not a Visual Studio plugin (since it runs on multiple OSes). The plugin just provides syntax highlighting, autoindentation, etc. It's not in the gallery yet since it is only very basic at the moment and doesn't yet provide things like intellisense.

**Comment by sherry-ummen** [comment]
I understand. Thank you for the response.
